#!/bin/bash
# declare STRING variable

#Execute as ./script FILE_TO_EXECUTE TITLE
exec &>> $2.log
#print variable on a screen


COUNT=5
COUNT_THREADS=3
FLAGS=4
THREADS=2
echo "$2"
#CON O SIN MAVX
while [ $FLAGS -gt 0 ]; do
	rm ani
	if [ $FLAGS -eq 4 ] ; then
		echo -ne "NO OPT-NO MAVX";
		gcc -o ani anidado.c -fopenmp
	fi
	if [ $FLAGS -eq 3 ] ; then
		echo -ne "NO OPT-MAVX";
		gcc -o ani anidado.c -fopenmp -mavx
	fi
	if [ $FLAGS -eq 2 ] ; then
		echo -ne "OPT-NO MAVX";
		gcc -o ani anidado.c -fopenmp -O3
	fi
	if [ $FLAGS -eq 1 ] ; then
		echo -ne "OPT-MAVX";
		gcc -o ani anidado.c -fopenmp -mavx -O3
	fi
	#Variable COUNT_THREADS
	COUNT_THREADS=3
	THREADS=2
	while [ $COUNT_THREADS -gt 0 ]; do

		echo -ne ",$THREADS threads,";
		export OMP_NUM_THREADS=$THREADS

		#CUENTA DE MUESTRAS POR TEST
		COUNT=5
		while [ $COUNT -gt 0 ]; do

	#echo Value of count is: $COUNT
	./$1
	#./ani > allout.txt 2>&1
	let COUNT=COUNT-1
done 
echo ""
let THREADS=THREADS*2
let COUNT_THREADS=COUNT_THREADS-1
done

let FLAGS=FLAGS-1
done


echo ""
