#!/bin/bash

rm -rf "$PWD/logs/secuencial.log"
exec &>> "$PWD/logs/secuencial.log"

filename="sec"

echo -ne "Secuencial";


arg1=(500)
arg2=(128 256 512 1024)


for i in ${arg1[@]}; do
	for j in ${arg2[@]}; do
		echo ""
		echo -ne "M:$i|B:$j,";
		#Variable Count
		COUNT=5
		while [ $COUNT -gt 0 ]; do
			./$filename $i $j
			let COUNT=COUNT-1
		done 
	done
done